const optionActionTypes = {
  SET_GROUP: "SET_GROUP",
  SET_GRADE: "SET_GRADE",
  SET_CURRENT_STUDENT_NAME: "SET_CURRENT_STUDENT_NAME",
  SET_REPORT_CARD_OPEN: "SET_REPORT_CARD_OPEN",
};

export default optionActionTypes;
