const optionActionTypes = {
  SET_GROUP: "SET_GROUP",
  SET_GRADE: "SET_GRADE",
  SET_CURRENT_STUDENT_INDEX: "SET_CURRENT_STUDENT_INDEX",
  SET_REPORT_CARD_OPEN: "SET_REPORT_CARD_OPEN",
  SET_FILTER_MODE: "SET_FILTER_MODE",
  SET_ONGOING_CASES: "SET_ONGOING_CASES",
  UPDATE_VEREDICT: "UPDATE_VEREDICT",
  UPDATE_PASSED_SUBJECT: "UPDATE_PASSED_SUBJECT",
};

export default optionActionTypes;
